#!/bin/bash

echo "PR Review Feature Test Guide"
echo "============================"
echo ""
echo "This feature allows you to review pull request comments and automatically"
echo "send them to Claude for processing."
echo ""
echo "How to test:"
echo "1. Make sure you have an active pull request with comments"
echo "2. Run the claude-squad application"
echo "3. Create or select an instance"
echo "4. Press 'R' to open the PR review interface"
echo "5. Use the following keys in the review interface:"
echo "   Navigation:"
echo "   - j/k or ↓/↑: Navigate between comments"
echo "   - PgUp/PgDn: Scroll the view"
echo "   - g/G: Go to first/last comment"
echo "   Actions:"
echo "   - a: Accept current comment"
echo "   - d: Deny current comment"
echo "   - A: Accept all comments"
echo "   - D: Deny all comments"
echo "   - Enter: Process accepted comments with Claude"
echo "   - q/Esc: Cancel and return"
echo "   - ?: Toggle help"
echo ""
echo "The accepted comments will be sent directly to the Claude AI pane for processing."
echo ""
echo "Requirements:"
echo "- GitHub CLI ('gh') must be installed and authenticated"
echo "- You must have an active pull request for the current branch"
echo "- The Claude instance must be in 'Ready' or 'Running' state"
echo ""
echo "What happens when you process comments:"
echo "1. Each accepted comment is formatted with context (author, file, line)"
echo "2. Comments are sent to Claude's AI pane (pane 1) one by one"
echo "3. Claude will analyze and address each review comment"
echo "4. There's a 2-second delay between comments to avoid overwhelming Claude"